apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-service-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: file-service-pv # Liên kết trực tiếp với PV đã tạo