apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-service-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/file-upload  # Đường dẫn trên node Kubernetes (máy host)
