apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8888                 # Port được sử dụng bên trong cluster
      targetPort: 8888          # Port trong container
      nodePort: 30088           # Port bạn có thể truy cập từ bên ngoài
